# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "checksigning2.xcodeproj")
    build_app(workspace: "checksigning2.xcworkspace", scheme: "checksigning2")
    upload_to_testflight
  end

  desc "Build the app"
  lane :build do
    match(type: "development", readonly: true)  # Fetch development certificates/profiles
    gym(workspace: "checksigning2.xcworkspace", scheme: "checksigning2")  # Build the app
  end
end
