default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "checksigning2.xcodeproj")
    build_app(
      workspace: "checksigning2.xcworkspace",
      scheme: "checksigning2",
      clean: true,
      xcargs: "-allowProvisioningUpdates"  # Cho phép cập nhật provisioning profiles tự động
    )
    upload_to_testflight
  end

  desc "Build the app"
  lane :build do
    build_app(
      workspace: "checksigning2.xcworkspace",
      scheme: "checksigning2",
      clean: true,
      xcargs: "-allowProvisioningUpdates"  # Tự động quản lý signing
    )
  end
end
